### ISSUE TITLE
C6 Silkscreen is backwards

### ISSUE THREAD

**Issue by IMI4tth3w** [Ryzee119/ogx360#1]
Hello!

During assembly of my ogx360 i noticed that the silkscreen for C6 is backwards.

See image from digikey
https://www.digikey.com/product-detail/en/panasonic-electronic-components/EEE-1CA100SR/PCE3878CT-ND/766254
https://media.digikey.com/pdf/Catalog%20Drawings/Capacitors/VS%20Series%20Bottom_B.jpg

It should "point" towards the positive rail.

**Comment by Ryzee119** [comment]
Are you sure? I'll double check but 3.3v is pointing 'down' towards the side of the USB type A connector

**Comment by Ryzee119** [comment]
https://imgur.com/EIvMkSR
Looks good to me

**Comment by IMI4tth3w** [comment]
You are right. I faslely assumed the big plane was ground. Thanks.

**Comment by Ryzee119** [comment]
all good :) let me know if you do find anything else
