### ISSUE TITLE
Parts list seems incorrect.

### ISSUE THREAD

**Issue by thalion777** [Ryzee119/ogx360#100]
![Screenshot_20221207_183221_Chrome](https://user-images.githubusercontent.com/120068615/206327996-89f896a4-9404-480a-a565-99c1e0d58105.jpg)

Not sure which part quantities are accurate, but i feel like 5 reset buttons is wrong...

**Comment by Ryzee119** [comment]
Most are rounded up to the nearest multiple of 5 except things that cost more than a few tens of cents

**Comment by thalion777** [comment]
Ok gotcha!  Btw, I can't for the life of me figure out what the TP1 - TP4 is.  All the videos I see on youtube has those 4 circles missing.

**Comment by thalion777** [comment]
Much appreciated friend.

**Comment by SavageCore** [comment]
> They're just test points for debugging. They are just exposed pads on the PCB that you can put a meter or oscilloscope onto
> 
> It's specifically for debugging the spi bus between the atmega and max3421

Ahn thank you. Should this be removed from the Kitspace interactive assembly guide?
