### ISSUE TITLE
Any alternative to the max3421?

### ISSUE THREAD

**Issue by Miggas** [Ryzee119/ogx360#102]
Hi,
Isn't there any possible cheaper alternative to the max3421?
For example a programable MCU with USB host capability and SPI, the max3421 is too expensive to buy multiple as they cost over 10€ (I'm from Portugal), and there are a lot of very capable MCUs like the rp2040 which costs a little over 1€.
Thanks

**Comment by Ryzee119** [comment]
See https://github.com/Ryzee119/ogx360_t4 which might be cheaper.

Unfortunately alot has changed in the last 4 years since I made this
