### ISSUE TITLE
MAX3421 invalid data read

### ISSUE THREAD

**Issue by CITRUS-Laim** [Ryzee119/ogx360#103]
I connected max3421 via 74hc125 
I have this error on test:
Ryzee119
ogx360 Testing Routine
Based on test routine by Circuits At Home
See https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/board_qc/board_qc.ino
MAX3421 Revision 03
SPI bus integrity test. Transfers 1MB of data. Each dot is 64K
Test failed.  Value written: 01 read: 00
Unrecoverable error - test halted!!
0x55 pattern is transmitted via SPI
Press RESET to restart test

**Comment by Ryzee119** [comment]
must be board error, soldering issue, faulty component. Can tell with information provided.
