### ISSUE TITLE
"Waiting for device" problem

### ISSUE THREAD

**Issue by Miggas** [Ryzee119/ogx360#104]
Hi, I've made a custom board and after assembling it and testing, no controllers where detected, I've already triple checked all connections to make sure everything is connected to the right pin and the solder joints are good, but I'm still getting this issue,
it stops on "Waiting for device" and stays there even with other controllers.
![Capture](https://user-images.githubusercontent.com/49589164/227722081-cc9d6d76-932e-4edc-be08-5b5ebd18555f.PNG)

Edit: I can upload my eagle files if you want to take a look

**Comment by Miggas** [comment]
[custom pcb.zip](https://github.com/Ryzee119/ogx360/files/11070542/custom.pcb.zip)
Here's the files anyway

**Comment by Ryzee119** [comment]
I can't really provide support for custom boards but check the USB port is getting 5V and the D+/- are the right way around

**Comment by Miggas** [comment]
Took a while, but I've found the problem, the voltage regulator ic was faulty and was supplying 4.9v instead of 3.3v, I replaced it and now it works fine. Even though the issue is closed, I'll leave this info here to help someone in case of the same problem.
