### ISSUE TITLE
QWERTY Chatpad obligatory? Or QWERTZ working too?

### ISSUE THREAD

**Issue by xfortknoxX** [Ryzee119/ogx360#105]
Hi Ryzee119,

I want to use the steel battalion controller emulation via wireless Xbox 360 controller Chatpad on my ogx360.
If you have a look on the GitHub entry, you say
"Make Sure you get a QWERTY Layout Chatpad".
So, is the QWERTY layout version obligatory to make it work or not?
Since I'm living in the QWERTZ region, it's hard to find a QWERTY chatpad.

Thank you

**Comment by Ryzee119** [comment]
It will 'work' but the button mapping logic based on the physical location of the buttons more so than the letter written on the key. So it will likely be very hard to confrol and not have anyt logic to it

Ofcourse it can be changed by changing the mapping from this point:
https://github.com/Ryzee119/ogx360/blob/cf04784d1f30a41834a44a1c2f05e8e6f0f3a593/Firmware/src/master.cpp#L245
