### ISSUE TITLE
Additonal buttons on the BOM?

### ISSUE THREAD

**Issue by qwertychouskie** [Ryzee119/ogx360#106]
The BOM has 5 of the [EG5350CT-ND](https://www.digikey.com/en/products/detail/e-switch/TL3305AF160QG/5816181) buttons, however, as far as I can tell, the board only has space for one button.  Is this a mistake or am I missing something?

**Comment by Ryzee119** [comment]
The BOM just rounded up to closest group of 5 or 10 units depending of price of the item

**Comment by qwertychouskie** [comment]
The number 5 directly comes from https://github.com/Ryzee119/ogx360/blob/master/.kitspace/bom.csv despite minimum order quantity being 1.  Now that I'm looking closer at it, many other components have higher numbers too (e.g. 5 clock crystals instead of one).

**Comment by Ryzee119** [comment]
Right it's just rounded up to closest 5 or 10 depending on price.
