### ISSUE TITLE
Add support for X360 microphones

### ISSUE THREAD

**Issue by JaviJJ117** [Ryzee119/ogx360#111]
Hello, it would be very useful to add compatibility with Xbox 360 microphones for online gaming.
It would be great if the standard headphones that connect with a jack to the controller and the wireless headphones that connect with Bluetooth to the Xbox 360 like the tritton warhead 7.1.
I'm sure it can be done.

**Comment by Ryzee119** [comment]
Max3421 host controller doesn't support isochronous USB transfers so it is not possible with this hardware unfortunately.

The atmega32u4 is also at capacity with its current feature set.

**Comment by JaviJJ117** [comment]
That is quite discouraging, is it possible that in the future you will release a second version of the ogx360 with different hardware capable of supporting isochronous USB transfers?
________________________________
De: Ryzee119 ***@***.***>
Enviado: lunes, 25 de septiembre de 2023 14:25
Para: Ryzee119/ogx360 ***@***.***>
Cc: SeñorXbox ***@***.***>; Author ***@***.***>
Asunto: Re: [Ryzee119/ogx360] Add support for X360 microphones (Issue #111)


Max3421 host controller doesn't support isochronous USB transfers so it is not possible with this hardware unfortunately.

The atmega32u4 is also at capacity with its current feature set.
