### ISSUE TITLE
Black & white buttons

### ISSUE THREAD

**Issue by CroCop86** [Ryzee119/ogx360#14]
Hey Ryze, me again :p 

i have a problem now and hopefully you can help me again. The black & white Button from the original controller, is it possible to get them to work with the x360 Controller too? There is a navigation menu, that will open when you press the white button on the original controller in xmbc. 
I could not find a way to open it up with another controller.

**Comment by Ryzee119** [comment]
Try the left and right bumpers. They are mapped to the black and white buttons

**Comment by CroCop86** [comment]
Strange, now it's working, thank you again :)
