### ISSUE TITLE
USB Hub to Join 

### ISSUE THREAD

**Issue by Gunnar-GO** [Ryzee119/ogx360#16]
Hi,

since the XBOX Connector is nothing more and less as a USB in an other form, **couldn't the connector join the up-to four controller in an usb hub?** After that just one cable is needed to connect all controller to the XBOX, the other ports would be free to leave DVD Playback Kit connected, or the adapter for usb memory or or or... 

Sadly i don't own an ogx360, so the topic is more theoretically.

**Comment by Kekule-OXC** [comment]
no.  that is not possible

**Comment by Ryzee119** [comment]
Answered here. I dont think it is possible without kernel patches which is outside the scope of this project.
