### ISSUE TITLE
3rd party wireless receiver doesn't work

### ISSUE THREAD

**Issue by MattNgo** [Ryzee119/ogx360#17]
Hey Ryzee,

[3rdParty-x360receiver.txt](https://github.com/Ryzee119/ogx360/files/3760170/3rdParty-x360receiver.txt)
This adapter was sourced from Amazon under the brand QUMOX. The 360 controller doesn't sync to it when plugged into the ogx360, but works fine on my PC.

**Comment by Ryzee119** [comment]
Hi, I think I just added this one last month

Can you confirm you have updated the firmware within the past few weeks?

**Comment by MattNgo** [comment]
The updated firmware solved the issue. I guess I just assumed it was the latest firmware since I just received it a few days ago!

Thanks again.
