### ISSUE TITLE
Firmware update not working - Windows 10. 

### ISSUE THREAD

**Issue by mrDevGit** [Ryzee119/ogx360#27]
Hi,

Amazing work, thanks for making this possible. It al works but I have no SB support at the moment.

Bought the full setup off Chimeric Systems. 4 boards with usb adapters.

I am trying to flash the firmware that will enable SB support.

However, when I connect the master board via USB it pops up as an "Unknown Device" on a WIndows 10 laptop.

It never shows up as a COM Port.

How do I resolve this?

Thanks

**Comment by mrDevGit** [comment]
I thought the reset was just to give you another shot but you have to press reset really quickly after connecting via USB.

Works perfectly.

**Comment by Ryzee119** [comment]
Im glad you worked it out. Apologies for not getting back to you!
You can also try double pressing the RESET button in quick succession.
Some of these Arduinos come with slightly different bootloaders and the exact process to get into the bootloader changes slightly.
