### ISSUE TITLE
Request/Info Curiosity - Can this be used with 

### ISSUE THREAD

**Issue by prozacgod** [Ryzee119/ogx360#4]
"SparkFun USB Host Shield"

https://www.sparkfun.com/products/9947

+ an arduino pro micro?  (at least for one controller)

It looks like this could work, as your schematic looks very similar to theirs.  This would save a LOT of time soldering for myself.

(I think I'm going to order these parts in anticipation that it will work :P)

**Comment by Ryzee119** [comment]
That will work just fine. Infact that exact part was involved in my very early prototypes.

**Comment by Ryzee119** [comment]
Closed , no action is required.
