### ISSUE TITLE
Question about modifications to XBOXONE.cpp

### ISSUE THREAD

**Issue by jimnarey** [Ryzee119/ogx360#42]
Hi - much like Phantom8 (see earlier issue you replied to) I have been trying to build a simplified version of the adapter for one wired controller at a time. I have a relatively quick question - why is rumble disabled in the modified version of XBOXONE.cpp included as part of the USB Host Library?

Thanks.

**Comment by Ryzee119** [comment]
I recall it was an issue with wired xbone rumble drawing too much power and causing ogx360 to reboot

**Comment by jimnarey** [comment]
That makes sense, thank you.

**Comment by jimnarey** [comment]
I now understand the code a bit better. The modifications to XBOXONE.cpp (seem to?) just prevent a rumble taking place on init. However, you were right about the power - a longish rumble was enough to hang the device so in my fork of your project I've disabled it via settings.h.

Thanks again!
