### ISSUE TITLE
Xbox One Wireless Adapter for Windows 10 (model 1790)

### ISSUE THREAD

**Issue by mmillar-bolis** [Ryzee119/ogx360#57]
Greetings!

I happen to have one of [these adapters](https://www.xbox.com/en-US/accessories/adapters/wireless-adapter-windows) from Microsoft that I would love to donate to you. I would be happy to pay for shipping as well. Of course your time is your own, but do you have any interest in introducing wireless support for this adapter?

Granted, I don't know whether there are any complications in adding yet another adapter onto the OGX code, but I thought that getting the device in your hands may give it a better purpose than just sitting here on my shelf. It's so compact that I would assume others would be interested as well.

Anyway, let me know and feel free to say no! :D

**Comment by turntablez123** [comment]
I would be interested in this as well!  I would donate for the ability to have the Xbox one dongle work on the ogxbox!

**Comment by Ryzee119** [comment]
Ive looked into this a bit already. Ref https://github.com/Ryzee119/ogx360/issues/6

At this point in time the atmega32u4 chips used on the ogx360 are simply not capable of supporting this alongside everything it already does unfortuntaely.
