### ISSUE TITLE
Could this be used to create third party/home made Steel Battalion controllers?

### ISSUE THREAD

**Issue by AstraleAmalthea** [Ryzee119/ogx360#61]
Greetings. Stumbled upon your project, and it’s a bit over my head. As I understand it, it converts inputs from a wireless game pad (and some other game pads) to original Xbox ports. 

Would it be possible to build a custom twin stick arcade setup with the correct amount of buttons, and use this to convert its inputs to steel battalion?

Basically, build a box, slap some buttons, sticks and throttles into it, then wire it up to one micro usb out and use this to play?

**Comment by Ryzee119** [comment]
Am closing this issue as its not really a project issue.
