### ISSUE TITLE
JLCPCB assembly?

### ISSUE THREAD

**Issue by CoolOppo** [Ryzee119/ogx360#66]
Hi! I would really like to just order a fully assembled PCB version from you, even if it's more expensive than doing it myself, to support the project, but (understandably) it doesn't look like it's something you offer. The next best thing for me would be to just get it fully assembled by JLCPCB. As you may or may not know, JLCPCB has support for submitting a couple extra files, and having them fully assemble an uploaded board. Are the files here compatible with this?

Some recommended (by me) links for ease:

[YouTube video showing how to prepare KiCad files for assembly from JLCPCB](https://www.youtube.com/watch?v=VejO8rDdhzo) (awesome vid, I've watched it all the way through)
[Official link from JLCPCB for how to get assembly services with KiCad](https://support.jlcpcb.com/article/84-how-to-generate-the-bom-and-centroid-file-from-kicad)

This could also be something you could use to get a bunch ordered so you can send them out to people! If you had some pre-assembled versions, I would _easily_ have bought one for like $60, and I bet you could get them for way, way less than that from JLCPCB, fully assembled, so just something to consider maybe!

**Comment by Ryzee119** [comment]
Thanks for the suggestion! Also appreciate your support of the project.

Im familiar with jlpcb services but currently don't plan on making/selling more at this stage.

The easiest way to order them is via kitspace https://kitspace.org/boards/github.com/ryzee119/ogx360/

Just a few clicks and you're on your way but requires self assembly. There's quite a few sellers around who have supported the project in one way or other too if you just want fully assembled 😊
