### ISSUE TITLE
Error loading files in KiCad 5.1.10

### ISSUE THREAD

**Issue by CoolOppo** [Ryzee119/ogx360#67]
When attempting to load up the files to check them out, KiCad spits out some errors.

Opening .brd:
![image](https://user-images.githubusercontent.com/1498177/122630346-df96c480-d090-11eb-9045-5149ff83c8c8.png)

Opening .sch:
![image](https://user-images.githubusercontent.com/1498177/122630370-081ebe80-d091-11eb-98b2-cb3bc24e8476.png)

**Comment by CoolOppo** [comment]
Oh, looks like maybe these weren't written in KiCad in the first place, my bad! If I'm wrong please reopen!

**Comment by Ryzee119** [comment]
Correct, they were made on Autodesk Eagle so you need to use that program.

KiCAD may have an option to import/convert these files but I'm not sure.
