### ISSUE TITLE
Bill of materials?

### ISSUE THREAD

**Issue by Electric1447** [Ryzee119/ogx360#70]
I remember being a link to digikey with all parts need for this project listed.
Was it removed or am I just blind?

**Comment by Electric1447** [comment]
On a different note I have multiple Mayflash adapters and q ridiculous amount of controllers, I would love to contribute to this amazing project.

**Comment by Ryzee119** [comment]
See hardware folder readme. I use kitspace to simplify ordering via digikey/gerbers

https://kitspace.org/boards/github.com/ryzee119/ogx360

**Comment by Ryzee119** [comment]
Have you tried the mayflash adaptors? If they're xinput compatible it may just work

**Comment by Electric1447** [comment]
They have an xinput mode

**Comment by Downcraft** [comment]
Hi, first of all thank you for this awesome project. Do you have an alternative for the max3421 controller? I have a hard time getting one. I tried digikey/aliexpress/amazon and some other sellers it seems to be sold out.

**Comment by Ryzee119** [comment]
Max3421 is critical to providing the usb host functionality and all the code is based around that chipset. So this project relies on it and it cannot easily be substituted. 

I suspect the global chip shortage is not helping supply.
