### ISSUE TITLE
Possible port to Raspberry Pi?

### ISSUE THREAD

**Issue by avibodek** [Ryzee119/ogx360#71]
To save on hardware, might it be possible to create something similar to the [Wiimote Controller Emulator](https://github.com/rnconrad/WiimoteEmulator)?

Granted, since Steel Battalion is 6th gen, I can imagine a PCB still might be necessary to get the wiring done.

**Comment by Ryzee119** [comment]
Raspi Zero has USB OTG if I remember correctly. This could be used, but running a full Linux system will not guarantee low latecy.

In anycase, there is possibilies for this but it is out of the scope of this project. Thanks for the suggestion.
