### ISSUE TITLE
Materials 

### ISSUE THREAD

**Issue by florezsebas** [Ryzee119/ogx360#72]
Can I use components of another manufacturer while this components has the same values like volt, capacitance, resistance?
Sorry for my ignorance about this, but I don't know much about electronics

**Comment by Ryzee119** [comment]
Yea pretty much.

Most parts are nothing special. The crystal oscillator and the diodes may want extra attention. 

The crystal should have matching load capacitance for example.

**Comment by Crossfader84** [comment]
Hi, i have a question to the USB Controller IC.
The MAX3421EEHJ+T is not in stock and comes back early 2022, can i use the MAX3421EEHJ+ ?
Or is there an other optional IC. This is the only Part on my list that is not in stock :-(

**Comment by Ryzee119** [comment]
Whats the difference? The T is probably just something to do with packaging. So probably fine

**Comment by Crossfader84** [comment]
> Whats the difference? The T is probably just something to do with packaging. So probably fine

Thanks a lot, finally i can order and build the OG360 :-)
