### ISSUE TITLE
Xbox One wireless adapter support?

### ISSUE THREAD

**Issue by reminon** [Ryzee119/ogx360#73]
Do you know if it is possible to implement?

**Comment by Ryzee119** [comment]
Thanks for the suggestion.

Ref https://github.com/Ryzee119/ogx360/issues/57 and https://github.com/Ryzee119/ogx360/issues/6

"At this point in time the atmega32u4 chips used on the ogx360 are simply not capable of supporting this alongside everything it already does unfortuntaely."
