### ISSUE TITLE
xbox 360 internal RF module

### ISSUE THREAD

**Issue by johndoenulc** [Ryzee119/ogx360#8]
HI

Have you tried using a salvaged RF module from an xbox 360 with your adapter?

http://www.appliedcarbon.org/xboxrf.html

I'm thinking this might be useful for an internal mod

Thanks

**Comment by Ryzee119** [comment]
Some users have successfully used this and its USB interface is compatible with the ogx360. Just a matter of sending the serial commands to perform syncing etc.

**Comment by Ryzee119** [comment]
Closing as not really an issue, but still useful info.

**Comment by ll3macorn** [comment]
will this ever happen?
