### ISSUE TITLE
ogx360 can't start Steel Battalion

### ISSUE THREAD

**Issue by hpx1984** [Ryzee119/ogx360#81]
Dear Sir Ryzee119

i'm used USB Host board and 3.3v/8M pro-micro board(first time i use 5v/16M but it can't working) for build a ogx360 and it can worked for xbox360 pc wireless receiver and 8bitdo wireless receiver 
the FW is use this one
![image](https://user-images.githubusercontent.com/76941051/153745811-37c08944-c93b-4457-b53b-094a99fa7856.png)

now  i can't start Game of Steel Battalion, is it means this FW can not support the key map of Steel battalion, 
how i can fix my ogx360 board for support Steel battalion
![image](https://user-images.githubusercontent.com/76941051/153745838-f476e908-8d36-4d1e-8f79-6266252ce106.png)
![image](https://user-images.githubusercontent.com/76941051/153745884-3dfc8a64-eee0-400d-81e1-b7e232aa264a.png)

by the way in your OGX360 Project's Pro micro board is 5v/16Mhz ,right?

many thanks your support sir

**Comment by Ryzee119** [comment]
Get the latest fw from this github page.
Edit platformio.ini and change the 16mhz numbers to 8mhz and recompile and program

**Comment by Ryzee119** [comment]
Did you have any luck with the latest firmware?

**Comment by hpx1984** [comment]
Dear Sir Ryzee119

i had download the latest firmware in your project and i know how to change 16mhz to 8mhz in ini file 
and i also downloaded and installed Arduino tool in my PC but i don't know how to recompile to HEX file 
I may study how to use Arduino later 
or could you help for recompile a 8mhz HEX?

**Comment by hpx1984** [comment]
Dear Sir Ryzee119

i followed this guide try for compile a 8Mhz FW (i compile 16Mhz original FW first )
![image](https://user-images.githubusercontent.com/76941051/158054248-0f66ce83-e6b0-4cfa-9960-a6acb8709b94.png)

but got many error reported 
![image](https://user-images.githubusercontent.com/76941051/158054307-1ab4bbec-6854-404a-bd49-5132bddd7309.png)
![image](https://user-images.githubusercontent.com/76941051/158054332-2170c95b-4bb1-47c6-993a-b556606c8821.png)
![image](https://user-images.githubusercontent.com/76941051/158054350-f3e9d021-a41b-460b-91dd-44be1e39a204.png)

i will try to study on Visual Studio Code usage hope can know how to fix the problem

**Comment by hpx1984** [comment]
![image](https://user-images.githubusercontent.com/76941051/158054637-a6dde785-d089-4aec-8b05-6b119536d4fb.png)

**Comment by hpx1984** [comment]
Dear Sir Ryzee119

could you add one more FW version of 8Mhz in your next FW update release  
![image](https://user-images.githubusercontent.com/76941051/160379219-276060d7-f2b3-448e-88b0-1a0dd5638fdc.png)

now this FW can support PS3 controller so i think it also has possible for support PS3 Move controller for light gun play with House of the Dead , and I think the FW also is big challenge

**Comment by Ryzee119** [comment]
8Mhz wont be officially support by me as I am unable to test it properly and cant comment on the impact of it. 

Not finding Arduino.h header is not related and likely due to not cloning the repo properly.
