### ISSUE TITLE
???

### ISSUE THREAD

**Issue by EdwardDanielSalazar** [Ryzee119/ogx360#83]
there is possibility to use an already developed shield like this

https://www.google.com/search?q=Usb+Host+Shield+2.0+Max3421e+Google+Adk+Arduino+Uno+Mega&rlz=1C1ONGR_esCO992CO992&oq=Usb+Host+Shield+2.0+Max3421e+Google+Adk+Arduino+Uno+Mega&aqs=chrome..69i57j69i60l2.143j0j4&sourceid=chrome&ie=UTF-8

**Comment by Ryzee119** [comment]
Sure. If you paid it with the same Pro Micro board and wire it the same you could even use the same firmware.

**Comment by Ryzee119** [comment]
Closing issue as its not related to this repo.
