### ISSUE TITLE
ogx360 doesn't working ,need help

### ISSUE THREAD

**Issue by hpx1984** [Ryzee119/ogx360#86]
Dear Sir

i had build 2sets ogx360 but all can't working 
i used pro micro board 5v/16Mhz, test 2.0 and 2.1 FW , got same issue
when i plug ogx360 into xbox the green led turn on , i plug xbox360 controller or 8bitdo receiver into ogx360 
the xbox360 controller LED flash two times and then turn off, 360 controller doesn't working 

i checked the soldering workmanship and i didn't find any defect 
USB vcc is 4.8v
can any one help for comment where i can check or verify 
please help me 

![image](https://user-images.githubusercontent.com/76941051/167278944-61c2209c-c022-48ea-b3df-44d6edc74fdc.png)
![image](https://user-images.githubusercontent.com/76941051/167278893-f5fff062-be41-4e70-a5cb-2bda065991d5.png)
![image](https://user-images.githubusercontent.com/76941051/167278900-e56d27ca-ca74-4cd8-a832-727e87bb321b.png)
![image](https://user-images.githubusercontent.com/76941051/167278913-f41cdc9d-0d6c-477c-aff0-d4d52132e744.png)
![image](https://user-images.githubusercontent.com/76941051/167278922-d6dcd041-a873-49c3-967c-6d3b401544a5.png)
![image](https://user-images.githubusercontent.com/76941051/167278927-52752608-8e65-45d3-a981-a191ee4f9d2d.png)
![image](https://user-images.githubusercontent.com/76941051/167278935-d1222e1e-d362-4502-a334-bd98a1ae7f23.png)

**Comment by Ryzee119** [comment]
What value are the caps on the crystal? C2 and c3?

Alot of components look like substitutes so not sure if they are all suitable

**Comment by hpx1984** [comment]
Hi sir

it is 16p , but i Measured it actual it is 15p

i have some 0603 size's cap and resistor on hand ,the value is match the bom request so i use then
i try to buy 0805 component for replace these 0603 components

**Comment by hpx1984** [comment]
Hi Sir

now i used 0805 chip component for builded 3sets ogx360 still got same issue , the pro micro board just green LED on when i plug xbox360 wire controller into USB connector and the controller just flash two times LED on and then LED off
![image](https://user-images.githubusercontent.com/76941051/168299644-d8f27bff-a89c-4136-bb2c-e36988268176.png)

![image](https://user-images.githubusercontent.com/76941051/168295626-0156f90c-9a31-4758-b428-c0f5188f6011.png)

some times red led will flash on pro micro board , dis-connect 360 controller also keep red led flash
![image](https://user-images.githubusercontent.com/76941051/168299613-8df24161-2939-4fdd-aa08-b593a2c13b9c.png)

Material status
![image](https://user-images.githubusercontent.com/76941051/168300317-33e47336-f0f7-4351-9b7d-440272a7b5cc.png)
![image](https://user-images.githubusercontent.com/76941051/168300371-912bfe3f-582b-40ae-8a98-7ae94d7e8017.png)
![image](https://user-images.githubusercontent.com/76941051/168300476-df1abbd8-91ec-4b1b-9846-48d5977fb7d9.png)
![image](https://user-images.githubusercontent.com/76941051/168300542-35b675c4-2674-4697-bb41-7b73c306f04f.png)
NXP 74HC4050D
MAX3421EE
49SMD-12M
10uf smd e-cap

if you have any idea please comment and help me for fix 
many thanks Sir

**Comment by hpx1984** [comment]
missed one more component is MIC5219-3.3BM5(marking:LG33)

**Comment by Ryzee119** [comment]
The two lights on solid would indicate that is it working to me? Any news on this?

**Comment by hpx1984** [comment]
now my ogx360 can worked now ,after i use another crystal oscillator 
but i got another problem 
i use orange 8bitdo adaptor for pairing one PS4 controller and it can worked fine , then i add one more Arduino board for support 2nd controller but i can't pairing the 2nd PS4 controller , tried 2.1 and 2.15 FW and got same issue

**Comment by hpx1984** [comment]
360 controller can pairing 2sets, very thing fine , thanks your great project Sir
