### ISSUE TITLE
 fatal error: Arduino.h: No such file or directory

### ISSUE THREAD

**Issue by robbiejmsn** [Ryzee119/ogx360#89]
Sorry for the noob question. When i click build, why am i getting this error? 
 fatal error: Arduino.h: No such file or directory
also, is there a better way to ask questions like this or is github the best way?

**Comment by Ryzee119** [comment]
Not sure, you need to provide alot more info. Just tested my end and works no problem.

**Comment by Ryzee119** [comment]
My guess is your didnt clone the repo properly.

`Clone with git git clone https://github.com/Ryzee119/ogx360.git --recursive. Recursively!` from instructions page
