### ISSUE TITLE
original breaout boards

### ISSUE THREAD

**Issue by lucirgo** [Ryzee119/ogx360#92]
hello, Ryzee119 thanks for all the hard work.

i know the original breakout boards is in another project but I want to ask you directly and no thru tek,

I order from jlcpcb all the boards and the break out is not working correctly already, tried to solder 2 of them with no luck they look like they have a short circuit, I was thinking that probably I mess the micro sub soldering as these are the smallest but I tried to solder 1 without the MicroUSB to test, this board has the same issue, so do you know if there any issue with this board design or maybe It can't be repaired may be ripping some traces.

already test using the external USB connector thru the controller port and xbox360 works great I love it so far.

best regard

**Comment by Ryzee119** [comment]
Not sure what you mean by breakout boards but the ogx360 PCBs have been built by hundreds of people without issues. So it is likely a soldering issue.
