### ISSUE TITLE
8BitDo Media Remote Support

### ISSUE THREAD

**Issue by XeniumMods** [Ryzee119/ogx360#95]
8BitDo recently released the Xbox Media Remote
[https://www.8bitdo.com/media-remote-for-xbox/](url)

Would it be possible to add IR support to Player 1
and map out the buttons for the remote control?

I noticed you did something similar with the teensy.

**Comment by Ryzee119** [comment]
Id have to purchase one to investigate. Does it even communicate over USB?
It will likely be in the scope of the Teensy project as unfortunately the ogx360 is at full capacity.
