### ISSUE TITLE
Trouble programming 2nd module

### ISSUE THREAD

**Issue by bassybeats** [Ryzee119/ogx360#96]
I assume its likely something I am doing, I have built up 2 boards with 2 pro mini's each. 3/4 program fine with the firmware tool. The fourth however does not have the red light show when plugged in via usb and the reset button does not trigger the red light like the other 3 modules did. Does this indicate a faulty pro mini or something I have done wrong?

**Comment by Ryzee119** [comment]
faulty pro micro or its missing its bootloader firmware (happens sometimes particularly if a clone from aliexpress etc)

You can reprogram the bootloader but its not easy and requires soldering wires to the ISP programming pins and using an AVR programmer.
